ALTER TABLE ssh_log MODIFY COLUMN create_time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE ssh_log MODIFY COLUMN update_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL;
