
ALTER TABLE movie MODIFY COLUMN created_time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE movie MODIFY COLUMN updated_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE movie MODIFY COLUMN created_time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE movie MODIFY COLUMN updated_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL;
